helmDefaults:
  wait: true

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: promtail
    namespace: logging
    createNamespace: true
    chart: grafana/promtail
    version: 6.8.2
    values:
      - "values-promtail.yaml"
