config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
    http_basic_auth_password_file:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        preferred_ip_protocol: "ip4"
        basic_auth:
          username: "admin"
          password_file: "/grafana-password/grafana-password.txt"

extraSecretMounts:
   - name: grafana-password
     mountPath: /grafana-password/grafana-password.txt
     secretName: grafana-password
     subPath: "grafana-password.txt"

serviceMonitor:
  selfMonitor:
    enabled: true
    labels:
      release: prometheus
