- hosts: ipaserver
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
#    - name: install pip3
#      apt: name=python3-pip state=present
#    - name: Install multi python packages
#      pip:
#        name:
#          - docker
#          - docker-compose
  roles:
    - role: geerlingguy.docker
  post_tasks:
    - name: add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
    - name: reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection
    - name: Create directory /etc/docker-compose
      ansible.builtin.file:
        path: /etc/docker-compose
        state: directory
        owner: ubuntu
        group: ubuntu
    - name: Copy docker-compose.yaml
      ansible.builtin.copy:
        src: docker-compose.yaml
        dest: /etc/docker-compose/docker-compose.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy freeipa.packops.local.yaml
      ansible.builtin.copy:
        src: freeipa.packops.local.yaml
        dest: /etc/docker-compose/freeipa.packops.local.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy freeipa-pwd-portal.yaml
      ansible.builtin.copy:
        src: freeipa-pwd-portal.yaml
        dest: /etc/docker-compose/freeipa-pwd-portal.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
