---
- hosts: ipaserver
  become: true
  pre_tasks:
    - name: Install python3-pip
      apt:
        name:
          - python3-pip
        state: present
        update_cache: true
    - name: Install multi python packages with version specifiers
      pip:
        name:
          - docker
          - docker-compose
  roles:
    - role: geerlingguy.docker
