- hosts: ipaserver
  become: true
  pre_tasks:
    - name: Create directory /etc/docker-compose
      ansible.builtin.file:
        path: /etc/docker-compose
        state: directory
        owner: ubuntu
        group: ubuntu
    - openssl_privatekey:
        path: /etc/docker-compose/root.key
        size: 2048

    - openssl_csr:
        path: /etc/docker-compose/root.csr
        privatekey_path: /etc/docker-compose/root.key

    - openssl_certificate:
        provider: selfsigned
        path: /etc/docker-compose/root.crt
        privatekey_path: /etc/docker-compose/root.key
        csr_path: /etc/docker-compose/root.csr
