- hosts: ipaserver
  become: true
  vars:
    - server_hostname: apatsev.org.ru
    - key_size: 4096
    - passphrase: # Set if you want passphrase
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: KE
    - email_address: admin@apatsev.org.ru
    - organization_name: apatsev.org.ru
  pre_tasks:
    - name: Create directory /etc/docker-compose
      ansible.builtin.file:
        path: /etc/docker-compose
        state: directory
        owner: ubuntu
        group: ubuntu
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "/etc/docker-compose/{{ server_hostname }}_privkey.pem"
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        backup: yes
    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "/etc/docker-compose/{{ server_hostname }}.csr"
        privatekey_path: "/etc/docker-compose/{{ server_hostname }}_privkey.pem"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ server_hostname }}"
    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "/etc/docker-compose/{{ server_hostname }}_cert.pem"
        privatekey_path: "/etc/docker-compose//{{ server_hostname }}_privkey.pem"
        csr_path: "/etc/docker-compose/{{ server_hostname }}.csr"
        provider: selfsigned