auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  http_server_read_timeout: 180s
  http_server_write_timeout: 180s

common:
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  compactor_address: http://loki-write:3100

memberlist:
  join_members: ["loki-read", "loki-write"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

ingester:
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 3
      kvstore:
        store: memberlist
    final_sleep: 0s
  chunk_idle_period: 1h
  wal:
    enabled: true
    dir: /loki/wal
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /tmp/index
    cache_location: /tmp/boltdb-cache


limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 500
  ingestion_burst_size_mb: 500
  max_cache_freshness_per_query: '10m'
  max_query_series: 100000
  max_query_parallelism: 16
  split_queries_by_interval: 60m

chunk_store_config:
  max_look_back_period: 720h

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

query_range:
  align_queries_with_step: true
  max_retries: 10
  cache_results: true
  parallelise_shardable_queries: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

querier:
  engine:
    max_look_back_period: 720h
  query_ingesters_within: 2h
  query_timeout: 1200s

compactor:
  working_directory: /tmp/compactor
  shared_store: s3
