---
- hosts: lokiindocker
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: install pip3
      apt: name=python3-pip state=present
    - name: Install multi python packages with version specifiers
      pip:
        name:
          - docker
          - docker-compose
  roles:
    - role: geerlingguy.docker
  post_tasks:
    - name: Copy docker-compose-230.yml
      copy:
        src: docker-compose-230.yml
        dest: /home/ubuntu/docker-compose-230.yml
    - name: Copy docker-compose-261.yml
      copy:
        src: docker-compose-261.yml
        dest: /home/ubuntu/docker-compose-261.yml
    - name: Creates directory /home/ubuntu/config
      file:
        path: /home/ubuntu/config
        state: directory
    - name: Copy files of directory config to /home/ubuntu/config/
      copy:
        src: config/    # note the '/' <-- !!!
        dest: /home/ubuntu/config/
    - name: add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

