helmDefaults:
  wait: true

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    disableValidationOnInstall: true
    labels:
      name: kube-prometheus-stack
    version: 44.3.1
    values:
      - "values-kube-prometheus-stack-blackbox-exporter.yaml"
