- hosts: docker
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true
      when: ansible_os_family == 'Debian'
    - name: install pip3
      apt: name=python3-pip state=present
    - name: Install multi python packages with version specifiers
      pip:
        name:
          - docker
          - docker-compose
  roles:
    - role: geerlingguy.docker
  post_tasks:
    - name: add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Install packages git
      become: true
      package:
        name:
          - git
        state: present
    - name: git clone repo traefik-api
      ansible.builtin.git:
        repo: 'https://github.com/vasyakrg/traefik-api.git'
        dest: /traefik-api
