config:
  clients:
    - url: http://loki.apatsev.org.ru/loki/api/v1/push
  snippets:
    pipelineStages:
      - cri: {}
      - labeldrop:
          - filename
          - pod
      - json:
          expressions:
            method: method
            protocol: protocol
            status: status
      - labels:
          method:
          protocol:
          status:
      - output:
          source: output
