config:
  clients:
    - url: http://loki-loki-distributed-gateway.loki/loki/api/v1/push
  snippets:
    pipelineStages:
      - cri: {}
      - labeldrop:
          - filename
    extraScrapeConfigs: |
      # Add an additional scrape config for syslog
      - job_name: kubernetes-pods-name
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: drop
            regex: .+
          - action: keep
            regex: ambassador
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_namespace
