helmDefaults:
  wait: true

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-blackbox-exporter
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/prometheus-blackbox-exporter
    disableValidationOnInstall: true
    version: 7.5.0
    values:
      - "values-prometheus-blackbox-exporter.yaml"
