---
- name: prepare
  hosts: vault_instances
  become: true
  become_method: sudo
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Install jq
      apt:
        name: jq
    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['all'] %}
          {{ hostvars[host].ansible_host }} {{ host }}
          {% endfor %}
  roles:
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp
      hashicorp_installation_method: manual
      binary_repo: hc-mirror.express42.net
      hashicorp_products:
        - name: vault
          version: "1.9.4"
          type: oss
      _hashicorp_src:
        oss: "https://hc-mirror.express42.net/{{ item.name }}/{{ item.version }}/{{ item.name }}_{{ item.version }}_linux_{{ hashicorp_architecture_mapping }}.zip"
  post_tasks:
    - name: Create a directory /etc/vault.d
      file:
        path: /etc/vault.d
        state: directory
    - name: Creating an empty file vault.env
      ansible.builtin.file:
        path: /etc/vault.d/vault.env
        state: touch
    - name: Copy file vault.service
      ansible.builtin.copy:
        src: vault.service
        dest: /usr/lib/systemd/system/vault.service
        owner: root
        group: root
        mode: '0644'


- name: Assemble Vault cluster
  hosts: vault_instances
  any_errors_fatal: true
  become: true
  become_user: root
  gather_facts: true
  debugger: on_failed
  roles:
    - robertdebock.vault
  vars:
    vault_show_unseal_information: yes
    vault_install_package: no
    vault_store_root_token: yes
    vault_make_backup: no
    vault_leader: "{{ hostvars[groups['vault_instances'][0]].ansible_host }}"
    vault_listeners:
      - name: tcp
        address: "127.0.0.1:8200"
        cluster_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8201"
        tls_disable: "true"

      - name: tcp
        address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8200"
        cluster_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8201"
        tls_disable: "true"
    vault_log_level: "debug"
    vault_disable_clustering: "false"
    vault_api_addr: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8200"
    vault_cluster_addr: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8201"





  # vars:
    # vault_checksum_file_url: "https://hc-mirror.express42.net/vault/{{ vault_version }}/vault_{{ vault_version}}_SHA256SUMS"
    # vault_zip_url: "https://hc-mirror.express42.net/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
