#cloud-config
write_files:
  - content: |
        worker_processes  2;

        events {
            use           epoll;
            worker_connections  128;
        }

        error_log  /dev/stderr error;
        
        http {
            server_tokens off;
            include       mime.types;
            charset       utf-8;
            
            access_log    /dev/stdout      combined;
        
            server {
                server_name   localhost;
                listen        80;
                
                error_page    500 502 503 504  /50x.html;
                
                location      / {
                    root      html;
                }
            }
        }
    path: /nginx.conf
