---
- hosts: vm-single
  collections:
    - victoriametrics.cluster
  become: true
  roles:
    - role: cloudalchemy.node_exporter
      vars:
        node_exporter_version: 1.3.1
    - role: victoriametrics.cluster.vmagent
    - role: victoriametrics.cluster.single
    - role: buluma.grafana
