- hosts: docker
  become: true
  pre_tasks:
    - name: Install docker, docker-compose
      apt:
        name:
          - docker
          - docker-compose
        state: present
        update_cache: true
    - name: add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
