- hosts: docker
  become: true
  roles:
    - role: geerlingguy.docker
  post_tasks:
    - name: add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
