---
- hosts: sentry
  become: true
  pre_tasks:
    - name: Install python3-pip, nginx-full, git
      apt:
        name:
          - python3-pip
          - nginx-full
          - git
        state: present
        update_cache: true
    - name: Install multi python packages with version specifiers
      pip:
        name:
          - docker
          - docker-compose
  roles:
    - role: geerlingguy.docker
  post_tasks:
    - name: add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
    - name: git clone repo self-hosted
      ansible.builtin.git:
        repo: 'https://github.com/getsentry/self-hosted.git'
        dest: /root/self-hosted
        version: 22.12.0
    - name: Copy default nginx config
      copy:
        src: default
        dest: /etc/nginx/sites-available/default
    - name: Restart service nginx, also issue daemon-reload to pick up config changes
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: nginx
    - name: reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection
