#version: "3.9"

services:

  loki:
    image: grafana/loki:2.3.0
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - /etc/docker-compose/local-config.yaml:/etc/loki/local-config.yaml
      - loki:/loki
    ports:
      - "3100:3100"
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/metrics"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      loki:
        aliases:
          - loki

  cassandra:
    image: bitnami/cassandra:3.11.11
    restart: always
    volumes:
      - cassandra:/bitnami
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_CLUSTER_NAME: loki
      CASSANDRA_DATACENTER: dc1
    networks:
      loki:
        aliases:
          - cassandra

  log-generator:
    image: mingrammer/flog
    restart: always
    command:
      - --loop
      - --format=json
      - --number=10
      - --delay=100ms
      - --output=/var/log/generated-logs.txt
      - --overwrite
      - --type=log
    depends_on:
      promtail:
        condition: service_started
    volumes:
      - ./loki/:/var/log/

  promtail:
    image: grafana/promtail:2.6.1
    restart: always
    volumes:
      - ./loki/:/var/log/
      - ./config/promtail-old.yaml:/etc/promtail/promtail.yaml
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      loki:
        condition: service_started
    networks:
      loki:
        aliases:
          - promtail

  grafana:
    image: grafana/grafana:9.1.6
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./config/datasources-230.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana:/var/lib/grafana
    networks:
      - loki

volumes:
  cassandra:
  loki:
  grafana:

networks:
  loki:
    driver: bridge