helmDefaults:
  wait: true

repositories:
  - name: cert-manager
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: cert-manager/cert-manager
    version: 1.11.0
    set:
      - name: installCRDs
        value: true
