repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: 44.3.1
    values:
      - ingress:
          enabled: true
          path: /
          hostname: grafana.apatsev.org.ru
          ingressClassName: "nginx"
