- hosts: ipaserver
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
  roles:
    - role: geerlingguy.docker
  post_tasks:
    - name: add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
    - name: reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection
    - name: git clone repo openxpki-docker
      ansible.builtin.git:
        repo: 'https://github.com/openxpki/openxpki-docker.git'
        dest: /openxpki-docker

#    - name: Copy openxpki.service
#      ansible.builtin.copy:
#        src: openxpki.service
#        dest: /etc/systemd/system/openxpki.service
#        owner: ubuntu
#        group: ubuntu
#        mode: '0644'
#      register: openxpki_service
#
#    - name: Restart service openxpki
#      ansible.builtin.systemd:
#        state: restarted
#        daemon_reload: yes
#        name: openxpki
#      when: docker_compose.changed or openxpki_service
