alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 2h
      repeat_interval: 2h
      receiver: 'null'
      routes:
        - receiver: 'null'
          matchers:
            - severity=~"warning|critical|none"
          continue: true
        - receiver: 'send_email'
          matchers:
            - severity=~"warning|critical|none"
          continue: true
        - receiver: 'telega'
          matchers:
            - severity=~"warning|critical|none"
    receivers:
      - name: 'null'
      - name: 'send_email'
        email_configs:
          - to: "alert-to-email"
            from: "alert-from-email"
            smarthost: 'smtp.yandex.ru:587'
            auth_username: "alert-from-email"
            auth_password: "password for application"
            require_tls: true
            send_resolved: true
            headers:
              subject: '{{ range .Alerts }}{{.Labels.alertname}} {{ if eq .Status "firing" }} Problem23 {{ else if eq .Status "resolved" }} Ok23 {{end}} {{ end }}'
            html: |
              вариант 1:
              {{ range .Alerts }}
              <b>{{.Labels.alertname}}: {{ if eq .Status "firing" }} Problem {{ else if eq .Status "resolved" }} Ok {{end}}</b>

                Summary: {{ .Annotations.summary }}

                Description: {{ .Annotations.description }}

                Title: {{ .Annotations.title }}

                Runbook_url: {{ .Annotations.runbook_url }}

              {{ end }}

              вариант 2:
              {{ range .Alerts }}
              <p><b>{{.Labels.alertname}}: {{ if eq .Status "firing" }} Problem {{ else if eq .Status "resolved" }} Ok {{end}}</b>
                <ul>{{ range .Annotations.SortedPairs }}
                <li>{{ .Name }} = {{ .Value }}</li>
                {{ end }}</ul>
              {{ end }}
#            headers:
#              subject: '{{ if eq .Status "firing" }} Problem {{ else if eq .Status "resolved" }} Ok {{end}}'
#            html: |-
#              <h3>You have the following alerts:</h3>
#              {{ range .Alerts }}
#              <p><b>{{.Labels.alertname}}</b>
#                <ul>{{ range .Annotations.SortedPairs }}
#                <li>{{ .Name }} = {{ .Value }}</li>
#                {{ end }}</ul>
#                <ul>{{ range .Labels.SortedPairs }}
#                <li>{{ .Name }} = {{ .Value }}</li>
#                {{ end }}</ul>
#                {{ .GeneratorURL }}</p>
#              {{ end }}
      - name: 'telega'
        telegram_configs:
          - bot_token: "xxxxx:yyyyyy-zzzzzzz"
            api_url: 'https://api.telegram.org'
            chat_id: -nnnnnn
            message:  "Alertname: {{ .GroupLabels.alertname }}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
            parse_mode: 'HTML'
            send_resolved: true
  alertmanagerSpec:
    logLevel: debug
