alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 2h
      repeat_interval: 2h
      receiver: 'null'
      routes:
        - receiver: 'null'
          matchers:
            - severity=~"warning|critical|none"
          continue: true
        - receiver: 'telega'
          matchers:
            - severity=~"warning|critical|none"
    receivers:
      - name: 'null'
      - name: 'telega'
        telegram_configs:
          - bot_token: "xxxxx:yyyyyy-zzzzzzz"
            api_url: 'https://api.telegram.org'
            chat_id: -nnnnnn
            message:  "Alertname: {{ .GroupLabels.alertname }}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
            parse_mode: 'HTML'
            send_resolved: true
  alertmanagerSpec:
    logLevel: debug

grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - promgrafana.apatsev.org.ru
    path: /

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
