grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - promgrafana.apatsev.org.ru
    path: /
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-loki-distributed-gateway.loki
      jsonData:
        maxLines: 1000


prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    logFormat: json

alertmanager:
  alertmanagerSpec:
    logFormat: json

