#cloud-config
runcmd:
 - apt update
 - apt install -y gnupg 
 - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
 - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
 - apt update
 - apt install -y mongodb-org
 - mkdir -p /usr/local/share/ca-certificates/Yandex && wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" -O /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt
