- hosts: ipaserver
  become: true
  vars:
    - key_size: 4096
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: RU
    - email_address: admin@apatsev.org.ru
    - organization_name: APATSEV

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Create directory /etc/docker-compose
      ansible.builtin.file:
        path: /etc/docker-compose
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Create directory /etc/docker-compose/freeipa-certificate
      ansible.builtin.file:
        path: /etc/docker-compose/freeipa-certificate
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Create directory /etc/docker-compose/ca
      ansible.builtin.file:
        path: /etc/docker-compose/ca
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

  roles:
    - role: geerlingguy.docker
  post_tasks:

    - name: add user ubuntu to docker group
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        groups: docker
        append: yes

    - name: reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection
