- hosts: ipaserver
  become: true
  vars:
    github_user: "smallstep"
    github_repo: "cli"
    download_dir: "/home/ubuntu"
    step_ca_version: "0.25.2"
  pre_tasks:
    - name: Get URL of latest Step CLI
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ github_user }}/{{ github_repo }}/releases/latest
        body_format: json
        return_content: true
        remote_src: true
      register: json_response

    - name: Debug json_response
      ansible.builtin.debug:
        msg: "{{ (json_response.json.assets | selectattr('browser_download_url', 'search', 'step_linux_amd64.tar.gz') | list | first).browser_download_url }}"

    - name: Get latest release of Step CLI
      ansible.builtin.unarchive:
        src: "{{ (json_response.json.assets | selectattr('browser_download_url', 'search', 'step_linux_amd64.tar.gz') | list | first).browser_download_url }}"
        dest: /usr/local/bin
        remote_src: true
        extra_opts: [--strip-components=2]
        creates: /usr/local/bin/step

    - name: Remove files of Step CLI
      ansible.builtin.file:
        state: "absent"
        path: "{{ item }}"
      with_items:
        - /usr/local/bin/bash_autocomplete
        - /usr/local/bin/README.md
        - /usr/local/bin/zsh_autocomplete
