- hosts: ipaserver
  become: true
  vars:
    - key_size: 4096
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: RU
    - email_address: admin@apatsev.org.ru
    - organization_name: APATSEV

  pre_tasks:
    - name: Get step-ca latest tag 
      community.general.github_release:
        user: step-ca
        repo: step-ca
        action: latest_release
      register: step_ca_latest 

    - name: Grab step-ca latest binaries 
      unarchive: 
        src: "https://github.com/step-ca/step-ca/releases/download/{{ step_ca_latest['tag'] }}/step-ca_{{ step_ca_latest['tag'] | regex_replace('^v','') }}_linux_amd64.zip"
        dest: /usr/local/bin
        remote_src: true

    - name: Set permissions for the step-ca
      ansible.builtin.file:
        path: /usr/local/bin/step-ca
        mode: 'u+x,g+x'
