- hosts: ipaserver
  become: true
  vars:
    github_user: "smallstep"
    github_repo: "certificates"
    download_dir: "/home/ubuntu"
  pre_tasks:
    - name: Get latest release information
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ github_user }}/{{ github_repo }}/releases/latest"
        return_content: true
      register: latest_release

    - name: Extract download URL for the latest release
      ansible.builtin.set_fact:
        download_url: "{{ latest_release.json.assets[0].browser_download_url }}"

    - name: Download latest binary release
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "{{ download_dir }}/{{ github_repo }}.tar.gz"
        mode: '0644'

    - name: Extract tar.gz archive
      ansible.builtin.unarchive:
        src: "{{ download_dir }}/{{ github_repo }}.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        # creates: "/usr/local/bin/step-ca"
