auth_enabled: true

http_prefix:

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_server_read_timeout: 150m
  http_server_write_timeout: 150m
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks/
      rules_directory: /loki/rules

memberlist:
  join_members: ["loki-read", "loki-write"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

ingester:
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
    final_sleep: 0s
  chunk_idle_period: 1h
  wal:
    enabled: true
    dir: /loki/wal
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 20m
  flush_op_timeout: 10s

schema_config:
  configs:
    - from: 2021-08-19
      store: cassandra
      object_store: filesystem
      schema: v11
      index:
        prefix: cassandra_table
        period: 24h

storage_config:
  cassandra:
    username: cassandra
    password: cassandra
    addresses: cassandra
    consistency: ONE
    auth: true
    keyspace: loki
  filesystem:
    directory: /loki/chunks
  index_queries_cache_config:
    redis:
      endpoint: redis:6379
      expiration: 1h

limits_config:
  max_cache_freshness_per_query: '10m'
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 500
  ingestion_burst_size_mb: 500
  max_streams_per_user: 500000
  max_concurrent_tail_requests: 20
  max_query_series: 100000
  max_query_parallelism: 64
  # parallelize queries in 15min intervals
  split_queries_by_interval: 24h

chunk_store_config:
  max_look_back_period: 720h
  cache_lookups_older_than: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

query_range:
  align_queries_with_step: true
  max_retries: 5
  parallelise_shardable_queries: true
  cache_results: true
  results_cache:
    cache:
      redis:
        endpoint: redis:6379
        expiration: 48h
        db: 0

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 2048

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

querier:
  engine:
    timeout: 150m
    max_look_back_period: 150m
  query_ingesters_within: 3h
  max_concurrent: 25
  query_timeout: 150m
  extra_query_delay: 30s
