helmDefaults:
  wait: true

repositories:
  - name: archive-full-bitnami
    url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami

releases:
  - name: grafana
    namespace: grafana
    createNamespace: true
    chart: archive-full-bitnami/grafana
    version: 8.2.22
    values:
      - ingress:
          enabled: true
          hostname: grafana.apatsev.org.ru
          annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: ca-issuer
          tls:
            - secretName: grafana-cert
              hosts:
                - grafana.apatsev.org.ru