helmDefaults:
  wait: true

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: grafana
    createNamespace: true
    chart: grafana/grafana
    version: 6.50.0
    values:
      - ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: ca-issuer
          hosts:
            - grafana.apatsev.org.ru
          tls:
            - secretName: grafana-cert
              hosts:
                - grafana.apatsev.org.ru
