version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - 'redis-server'
      - '--databases 1'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory 1gb'
      - '--maxmemory-policy allkeys-lru'
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      loki:
        aliases:
          - redis

  init:
    image: grafana/loki:2.7.3
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - loki:/loki
    networks:
      - loki
    depends_on:
      redis:
        condition: service_healthy
      cassandra:
        condition: service_healthy

  grafana:
    image: grafana/grafana:9.1.6
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - loki

  log-generator:
    image: mingrammer/flog
    command:
      - --loop
      - --format=json
      - --number=10
      - --delay=100ms
      - --output=/var/log/generated-logs.txt
      - --overwrite
      - --type=log
    volumes:
      - ./loki/:/var/log/
    depends_on:
      promtail:
        condition: service_started

  promtail:
    image: grafana/promtail:2.7.3
    volumes:
      - ./loki/:/var/log/
      - ./config:/etc/promtail/
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - loki
    depends_on:
      loki-gateway:
        condition: service_started

  loki-gateway:
    image: nginx:1.19
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "3100"
    networks:
      - loki
    depends_on:
      loki-read:
        condition: service_started
      loki-write:
        condition: service_started

  loki-read:
    image: grafana/loki:2.7.3
    volumes:
      - ./config:/etc/loki/
      - loki:/loki
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/loki.yaml -target=read"
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      init:
        condition: service_completed_successfully

  loki-write:
    image: grafana/loki:2.7.3
    volumes:
      - ./config:/etc/loki/
      - loki:/loki
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/loki.yaml -target=write"
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      init:
        condition: service_completed_successfully

  table-manager:
    image: grafana/loki:2.7.3
    volumes:
      - ./config:/etc/loki/
      - loki:/loki
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/loki.yaml -target=table-manager"
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      init:
        condition: service_completed_successfully

  cassandra:
    image: bitnami/cassandra:3.11.11
    container_name: cassandra
    volumes:
      - cassandra:/bitnami
    restart: always
    healthcheck:
      test: [ "CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "SELECT table_name FROM system_schema.tables WHERE keyspace_name='loki';" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_CLUSTER_NAME: loki
      CASSANDRA_DATACENTER: dc1
    networks:
      loki:
        aliases:
          - cassandra

volumes:
  cassandra:
  loki:
  redis_data:

networks:
  loki:
    driver: bridge
