version: '2'

services:
  freeipa:
    image: freeipa/freeipa-server:fedora-25
    container_name: freeipa
    restart: unless-stopped
    hostname: sanctuary
    domainname: serv.sanctuary.local
    extra_hosts:
      - "freeipa.local.xetus.com:172.16.1.10"
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "datavol:/data"
#      - "./server/ipa-volume:/root/shared"
#      - "./server/config:/root/pw-portal/config"
    command:
      - --admin-password=YOURPASSWORD
      - --auto-forwarders
      - --domain=local.xetus.com
      - --ds-password=YOURPASSWORD
      - --ip-address=172.16.1.10
      - --realm=LOCAL.XETUS.COM
      - --setup-dns
      - --unattended
    environment:
      IPA_SERVER_IP: "172.16.1.10"
    networks:
      priv_network:
        ipv4_address: 172.16.1.10

volumes:
  datavol:

networks:
  priv_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1