architecture: standalone
master:
  service:
    type: ClusterIP
    port: 6379
  persistence:
    enabled: false
  resources:
    limits:
      memory: 3000Mi
      cpu: 1000m
    requests:
      memory: 3000Mi
      cpu: 1000m
commonConfiguration: |-
  maxmemory 450mb
  maxmemory-policy allkeys-lru

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
